service: checkip
provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
functions:
  index:
    handler: handler.index
    events:
      - http:
          path: /
          method: get
          cors: true
  check:
    handler: handler.check
    events:
      - http:
          path: /{path*}
          method: get
          cors: true
plugins:
  - serverless-offline
